### ISSUE TITLE
Showing the year modal at the start.

### ISSUE THREAD

**Issue by rbozan** [roto93/react-native-neat-date-picker#13]
Hi,

https://github.com/roto93/react-native-neat-date-picker/blob/d94a59c01d8cb4b97143929c9050a7c2d7932fb8/src/components/NeatDatePicker.js#L32

In this line, we have an use case where we would like to first show the year and then show the date picker. It would be nice if a prop could be given, like `showYearModal` and this would show the year modal at first.

**Comment by roto93** [comment]
Hi, Sorry for the late reply. I have been fulfilling the military service in my country therefore could not reply for weeks.

Your advice is awesome! That would be more reasonable in many circumstances.

But I won’t be able to deal with it until June. It will be great if someone make a PR for it first. Otherwise please wait for few more days.

**Comment by roto93** [comment]
Version `1.4.9` added a new prop `chooseYearFirst`. I think this is what you need.😄
