### ISSUE TITLE
Application Not Showing anything after I Installed this Library

### ISSUE THREAD

**Issue by muqeet98** [roto93/react-native-neat-date-picker#5]
![Simulator Screen Shot - iPhone 11 - 2021-11-23 at 12 32 51](https://user-images.githubusercontent.com/40955420/142985595-d59f54a5-ed3a-4aec-b1c3-b56b2b0d61fd.png)

**Comment by roto93** [comment]
Hi, could you provide your code? 
Since I use react-native-modal under the hood, the date picker won't show up if it is NOT opened, i.e. `isVisible={false}` Maybe it is the reason.
You have to use a component like `<Button/>` to modify the `isVisible` prop. Let me know if it helps.

**Comment by roto93** [comment]
Hi @muqeet98, sorry for my misunderstaning, I think I solved this issue. 
This bug is Expo project only. The thing is that one of the dependencies I included, react-native-modal `v13.0.0`, requires React Native >= `0.65`. But even the latest version of Expo today (SDK 43) includes React Native `0.64.3` which is not compatible. Therefore I downgrade the react-native-modal dependency from `v13.0.0` to `v12.1.0`. Now it should work.
Please upgrade this package to `v1.1.3`. If the problem still exists, feel free to reopen this issue.
